name: espo_contacts
description: Contacts synchronizer for espoCrm

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.2
  fish_redux: ^0.2.6
  cached_network_image: ^1.1.1
  timeago: ^2.0.20
  url_launcher: 5.1.4
  logging: ^0.11.3+2
  http: ^0.12.0+2
  http_auth: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


flutter:

  uses-material-design: true

  assets:
    - res/images/